version: '3'

networks:
  backendC:

services:
  nginx:
    container_name: backendCnginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8333:80"
    networks:
      - backendC
    depends_on:
      - php
      - mysql
      - npm
      - composer
      - phpmyadmin
      - artisan
  mysql:
    container_name: backendCmysql
    image: mysql:8.0.21
    restart: unless-stopped
    tty: true
    env_file:
      - mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backendC
    ports:
      - "4403:3306"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backendCphp
    volumes:
      - ./src:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - backendC
  phpmyadmin:
    container_name: backendCphpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - phpmyadmin.env
    depends_on:
      - php
      - mysql
    ports:
      - "8803:80"
    networks:
      - backendC
  composer:
    container_name: backendCcomposer
    image: composer:1.10.10
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backendC
  npm:
    container_name: backendCnpm
    image: node:14.8.0
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    depends_on:
      - php
    networks:
      - backendC
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backendCartisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      backendC: